"""
Analizamos la paqueteríaa PDEParams.py
"""


import pandas as pd
import matplotlib.pyplot as plt

# Used in the definition of the model and its initial condition
import numpy as np

# Used for plots other than those generated by the parameter estimation module
import matplotlib.pyplot as plt
import PDEparams as pde


def LotkaVolterra(z, t, a, b):
    '''The input z corresponds to the current state of the system, z = [x, y]. Since the input is in 1D, no
    pre-processing is needed.

    t is the current time.

    a and b correspond to the unknown parameters.
    '''

    x, y = z

    return [a * x * (1 - x) - b * x * y, b * x * y - y]

def initial_x():
    return 0.3

def initial_y():
    return 0.5
df = pd.read_csv('../LotkaVolterraData.csv')

my_model = pde.PDEmodel(df, LotkaVolterra, [initial_x, initial_y], bounds=[(2, 4), (0.5,2)],
                        param_names=[r'$a$', r'$b$'], nvars=2, ndims=0, nreplicates=3, obsidx=None, outfunc=None)

print(my_model.initial_condition)

"""
fig, ax = plt.subplots()
ax.scatter(df['0'],df['1'] , label = 'x')
ax.scatter(df['0'],df['2'] , label = 'y')
ax.legend()
plt.show()
"""

print(my_model.fit())
print(my_model.best_params)
print(my_model.best_error)
